#!/bin/sh

gnulib-tool					\
    --import					\
    --vc-files                                  \
    --symbolic                                  \
    --with-tests				\
    --libtool					\
    argp					\
    crypto/gc-random                            \
    crypto/gc-rijndael				\
    error					\
    getaddrinfo					\
    getpass					\
    xalloc

autoreconf --install --symlink
